version: "3.8"

services:
  diana-proxy:
    build:
      context: ./diana-proxy
      dockerfile: Dockerfile
    container_name: diana-proxy
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - RIOT_API_KEY=${RIOT_API_KEY:-API_KEY}
      - DATABASE_URL=${DATABASE_URL:-DATABASE_URL}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:4000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - diana-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  diana-network:
    driver: bridge
